// `.env.json` is generated by the `npm run build` command
import * as env from './.env.json';
import { environment as defaultEnvironment } from './environment.default';

export const environment: any = {
  ...defaultEnvironment,
  production: true,
  version: env.npm_package_version,
  // serverUrl: 'https://usa-government-info-backend.herokuapp.com/api',
  staticDataUrl: 'http://data.mapmyreps.us',
  showColorMixingOptions: false,
};
