// `.env.ts` is generated by the `env` package script
import env from './.env';
import { environment as defaultEnvironment } from './environment.default';

export const environment: any = {
  ...defaultEnvironment,
  production: true,
  version: env.npm_package_version,
  staticDataUrl: 'http://staging-data.mapmyreps.us',
};
