// `.env.json` is generated by the `npm run build` command
import * as env from './.env.json';
import { environment as defaultEnvironment } from './environment.default';

export const environment: any = {
  ...defaultEnvironment,
  production: true,
  version: env.npm_package_version,
  staticDataUrl: 'http://staging-data.mapmyreps.us',
};
